import { AdvanceTypes } from './advance-types.enum';

export const advancesList = [
    {
        id: 1,
        name: 'ADVANCED MILITARY',
        cost: 240,
        points: 6,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 20,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 5,
        discountToArts: 0
    },
    {
        id: 2,
        name: 'AGRICULTURE',
        cost: 120,
        points: 3,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 10,
        discountToReligion: 0,
        discountToScience: 5,
        discountToArts: 0
    },
    {
        id: 3,
        name: 'ANATOMY',
        cost: 270,
        points: 6,
        type1: AdvanceTypes.SCIENCE,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 5,
        discountToReligion: 0,
        discountToScience: 20,
        discountToArts: 0
    },
    {
        id: 4,
        name: 'ARCHITECTURE',
        cost: 140,
        points: 3,
        type1: AdvanceTypes.ARTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 5,
        discountToArts: 10
    },
    {
        id: 5,
        name: 'ASTRONAVIGATION',
        cost: 80,
        points: 1,
        type1: AdvanceTypes.SCIENCE,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 5,
        discountToScience: 10,
        discountToArts: 0
    },
    {
        id: 6,
        name: 'CALENDAR',
        cost: 180,
        points: 3,
        type1: AdvanceTypes.SCIENCE,
        type2: AdvanceTypes.NONE,
        discountToCivics: 5,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 10,
        discountToArts: 0
    },
    {
        id: 7,
        name: 'CARTOGRAPHY',
        cost: 160,
        points: 3,
        type1: AdvanceTypes.SCIENCE,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 10,
        discountToArts: 5
    },
    {
        id: 8,
        name: 'CLOTH MAKING',
        cost: 50,
        points: 1,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 10,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 5
    },
    {
        id: 9,
        name: 'COINAGE',
        cost: 90,
        points: 1,
        type1: AdvanceTypes.SCIENCE,
        type2: AdvanceTypes.NONE,
        discountToCivics: 5,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 10,
        discountToArts: 0
    },
    {
        id: 10,
        name: 'CULTURAL ASCENDANCY',
        cost: 280,
        points: 6,
        type1: AdvanceTypes.ARTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 5,
        discountToScience: 0,
        discountToArts: 20
    },
    {
        id: 11,
        name: 'DEISM',
        cost: 70,
        points: 1,
        type1: AdvanceTypes.RELIGION,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 5,
        discountToReligion: 10,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 12,
        name: 'DEMOCRACY',
        cost: 220,
        points: 6,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 20,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 5
    },
    {
        id: 13,
        name: 'DIASPORA',
        cost: 270,
        points: 6,
        type1: AdvanceTypes.RELIGION,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 20,
        discountToScience: 0,
        discountToArts: 5
    },
    {
        id: 14,
        name: 'DIPLOMACY',
        cost: 160,
        points: 3,
        type1: AdvanceTypes.ARTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 5,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 10
    },
    {
        id: 15,
        name: 'DRAMA AND POETRY',
        cost: 80,
        points: 1,
        type1: AdvanceTypes.ARTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 5,
        discountToScience: 0,
        discountToArts: 10
    },
    {
        id: 16,
        name: 'EMPIRICISM',
        cost: 60,
        points: 1,
        type1: AdvanceTypes.SCIENCE,
        type2: AdvanceTypes.NONE,
        discountToCivics: 5,
        discountToCrafts: 5,
        discountToReligion: 5,
        discountToScience: 10,
        discountToArts: 5
    },
    {
        id: 17,
        name: 'ENGINEERING',
        cost: 160,
        points: 3,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.SCIENCE,
        discountToCivics: 0,
        discountToCrafts: 10,
        discountToReligion: 0,
        discountToScience: 10,
        discountToArts: 0
    },
    {
        id: 18,
        name: 'ENLIGHTENMENT',
        cost: 160,
        points: 3,
        type1: AdvanceTypes.RELIGION,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 5,
        discountToReligion: 10,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 19,
        name: 'FUNDAMENTALISM',
        cost: 150,
        points: 3,
        type1: AdvanceTypes.RELIGION,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 10,
        discountToScience: 0,
        discountToArts: 5
    },
    {
        id: 20,
        name: 'LAW',
        cost: 150,
        points: 3,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 10,
        discountToCrafts: 0,
        discountToReligion: 5,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 21,
        name: 'LIBRARY',
        cost: 220,
        points: 6,
        type1: AdvanceTypes.SCIENCE,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 20,
        discountToArts: 5
    },
    {
        id: 22,
        name: 'LITERACY',
        cost: 110,
        points: 3,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.ARTS,
        discountToCivics: 10,
        discountToCrafts: 5,
        discountToReligion: 5,
        discountToScience: 5,
        discountToArts: 10
    },
    {
        id: 23,
        name: 'MASONRY',
        cost: 60,
        points: 1,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 10,
        discountToReligion: 0,
        discountToScience: 5,
        discountToArts: 0
    },
    {
        id: 24,
        name: 'MATHEMATICS',
        cost: 250,
        points: 6,
        type1: AdvanceTypes.SCIENCE,
        type2: AdvanceTypes.ARTS,
        discountToCivics: 10,
        discountToCrafts: 10,
        discountToReligion: 10,
        discountToScience: 20,
        discountToArts: 20
    },
    {
        id: 25,
        name: 'MEDICINE',
        cost: 140,
        points: 3,
        type1: AdvanceTypes.SCIENCE,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 5,
        discountToReligion: 0,
        discountToScience: 10,
        discountToArts: 0
    },
    {
        id: 26,
        name: 'METALWORKING',
        cost: 90,
        points: 1,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 5,
        discountToCrafts: 10,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 27,
        name: 'MILITARY',
        cost: 170,
        points: 3,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 10,
        discountToCrafts: 5,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 28,
        name: 'MINING',
        cost: 230,
        points: 6,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 20,
        discountToReligion: 0,
        discountToScience: 5,
        discountToArts: 0
    },
    {
        id: 29,
        name: 'MONARCHY',
        cost: 60,
        points: 1,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 10,
        discountToCrafts: 0,
        discountToReligion: 5,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 30,
        name: 'MONOTHEISM',
        cost: 240,
        points: 6,
        type1: AdvanceTypes.RELIGION,
        type2: AdvanceTypes.NONE,
        discountToCivics: 5,
        discountToCrafts: 0,
        discountToReligion: 20,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 31,
        name: 'MONUMENT',
        cost: 180,
        points: 3,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.RELIGION,
        discountToCivics: 0,
        discountToCrafts: 10,
        discountToReligion: 10,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 32,
        name: 'MUSIC',
        cost: 80,
        points: 1,
        type1: AdvanceTypes.ARTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 5,
        discountToScience: 0,
        discountToArts: 10
    },
    {
        id: 33,
        name: 'MYSTICISM',
        cost: 50,
        points: 1,
        type1: AdvanceTypes.RELIGION,
        type2: AdvanceTypes.ARTS,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 5,
        discountToScience: 0,
        discountToArts: 5
    },
    {
        id: 34,
        name: 'MYTHOLOGY',
        cost: 60,
        points: 1,
        type1: AdvanceTypes.RELIGION,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 10,
        discountToScience: 0,
        discountToArts: 5
    },
    {
        id: 35,
        name: 'NAVAL WARFARE',
        cost: 160,
        points: 3,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 10,
        discountToCrafts: 5,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 36,
        name: 'PHILOSOPHY',
        cost: 220,
        points: 6,
        type1: AdvanceTypes.RELIGION,
        type2: AdvanceTypes.SCIENCE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 20,
        discountToScience: 20,
        discountToArts: 0
    },
    {
        id: 37,
        name: 'POLITICS',
        cost: 230,
        points: 6,
        type1: AdvanceTypes.ARTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 0,
        discountToReligion: 5,
        discountToScience: 0,
        discountToArts: 20
    },
    {
        id: 38,
        name: 'POTTERY',
        cost: 60,
        points: 1,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 10,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 5
    },
    {
        id: 39,
        name: 'PROVINCIAL EMPIRE',
        cost: 260,
        points: 6,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 20,
        discountToCrafts: 0,
        discountToReligion: 5,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 40,
        name: 'PUBLIC WORKS',
        cost: 230,
        points: 6,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 20,
        discountToCrafts: 5,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 41,
        name: 'RHETORIC',
        cost: 130,
        points: 3,
        type1: AdvanceTypes.ARTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 5,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 10
    },
    {
        id: 42,
        name: 'ROADBUILDING',
        cost: 220,
        points: 6,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 20,
        discountToReligion: 0,
        discountToScience: 5,
        discountToArts: 0
    },
    {
        id: 43,
        name: 'SCULPTURE',
        cost: 50,
        points: 1,
        type1: AdvanceTypes.ARTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 5,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 10
    },
    {
        id: 44,
        name: 'THEOCRACY',
        cost: 80,
        points: 1,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.RELIGION,
        discountToCivics: 5,
        discountToCrafts: 0,
        discountToReligion: 5,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 45,
        name: 'THEOLOGY',
        cost: 250,
        points: 6,
        type1: AdvanceTypes.RELIGION,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 20,
        discountToReligion: 0,
        discountToScience: 5,
        discountToArts: 0
    },
    {
        id: 46,
        name: 'TRADE EMPIRE',
        cost: 260,
        points: 6,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 5,
        discountToCrafts: 20,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 47,
        name: 'TRADE ROUTES',
        cost: 180,
        points: 3,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 0,
        discountToCrafts: 10,
        discountToReligion: 5,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 48,
        name: 'UNIVERSAL DOCTRINE',
        cost: 160,
        points: 3,
        type1: AdvanceTypes.RELIGION,
        type2: AdvanceTypes.NONE,
        discountToCivics: 5,
        discountToCrafts: 0,
        discountToReligion: 10,
        discountToScience: 0,
        discountToArts: 0
    },
    {
        id: 49,
        name: 'URBANISM',
        cost: 50,
        points: 1,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.NONE,
        discountToCivics: 10,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 5,
        discountToArts: 0
    },
    {
        id: 50,
        name: 'WONDER OF THE WORLD',
        cost: 290,
        points: 6,
        type1: AdvanceTypes.CRAFTS,
        type2: AdvanceTypes.ARTS,
        discountToCivics: 0,
        discountToCrafts: 20,
        discountToReligion: 0,
        discountToScience: 0,
        discountToArts: 20
    },
    {
        id: 51,
        name: 'WRITTEN RECORD',
        cost: 60,
        points: 1,
        type1: AdvanceTypes.CIVICS,
        type2: AdvanceTypes.SCIENCE,
        discountToCivics: 5,
        discountToCrafts: 0,
        discountToReligion: 0,
        discountToScience: 5,
        discountToArts: 0
    },

]